[tool.poetry]
name = "cloudconfig"
version = "0.1.0"
description = ""
authors = ["Bryan Sieber <bsieber@mozilla.com>"]

[[tool.poetry.source]]
name = "mozilla-it"
url = "https://dp2-prod.appspot.com/pypi"

[tool.poetry.dependencies]
python = "^3.6.1"
google-cloud-firestore = "^1.7.0"
pyjson = "^1.3.0"
pyyaml = "^5.3.1"
jsonmerge = "^1.7.0"
cloudsecrets = "^0.0.2"

[tool.poetry.dev-dependencies]
behave = "^1.2.6"
mock = "^4.0.2"
mockito = "^1.2.1"
pre-commit = "^2.4.0"
pytest = "^5.4.2"
pytest-cov = "^2.9.0"
pytest-mock = "^3.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
