#!/bin/bash

set -ex

if [ "$TRAVIS_BRANCH" == "master" ]; then
  ENV=stage
  IMG=gcr.io/dp2-admin/github.com/mozilla-it/data-integrations:$TRAVIS_BRANCH
else
  ENV=$TRAVIS_BRANCH
  IMG=gcr.io/dp2-admin/github.com/mozilla-it/data-integrations:$TRAVIS_BRANCH
fi


mkdir ~/.docker

docker build -t $IMG .